"""
Module for reading OME_BIN/CST_OME file
"""
import numpy as np
from scipy.io import FortranFile

from ._dtypes import endian_symbol

__all__ = ["read_ome_bin", "read_cst_ome", "read_dome_bin"]


def read_ome_bin(fname, num_bands, num_kpoints, num_spins, endian="big"):
    """
    Read the `ome_bin` file.

    The `omb_bin` file contains the optical matrix elements generated by the `Spectral` task.
    Note that we return the data in the 'C' order with dimensions (num_spins, num_kpoints, 3, num_bands, num_bands)

    Args:
        fname: Name of the file.
        num_bands: Number of bands.
        num_kpoints: Number of kpoints.
        num_spins: Number of spins.
        endian: Endian - CASTEP build instruction defaults to big-endian.

    Returns:
        version: The version number stored in the file.
        header: Header part written in the file.
        om: Optical matrix with dimensions (num_spins, num_kpoins, 3, num_bands, num_bands)
    """

    esymbol = endian_symbol(endian)
    version_dtype = f"{esymbol}f8"
    header_dtype = f"{esymbol}S80"
    # Each complex number takes 2*8 bits - both real and imaginary parts are
    # double precision
    array_seg = f"{esymbol}(3,{num_bands},{num_bands})c16"

    om = np.zeros((num_spins, num_kpoints, 3, num_bands, num_bands), dtype=complex)
    with FortranFile(fname, header_dtype=np.dtype(f"{esymbol}u4")) as fhandle:
        version = fhandle.read_record(version_dtype)
        header = fhandle.read_record(header_dtype)[0].decode()
        for ki in range(num_kpoints):
            for si in range(num_spins):
                om[si, ki, :, :, :] = fhandle.read_record(array_seg)
    return version[0], header, om


def read_cst_ome(fname, num_bands, num_kpoints, num_spins, endian="big"):
    """
    Read the `cst_ome` file.

    The `cst_ome` file contains the optical matrix elements generated by the `Spectral` task.
    This is a legacy file format in which every single matrix element is written as its own
    Fortran record, so the file is a flat sequence of `<marker><c16><marker>` triplets. Rather
    than issuing one read per element, the whole file is mapped in one go with a structured
    dtype that steps over the record markers.

    Note that we return the data in the 'C' order with dimensions (num_spins, num_kpoints, 3, num_bands, num_bands)

    Args:
        fname: Name of the file, or a file-like object opened in binary mode.
        num_bands: Number of bands.
        num_kpoints: Number of kpoints.
        num_spins: Number of spins.
        endian: Endian - CASTEP build instruction defaults to big-endian.

    Returns:
        om: Optical matrix with dimensions (num_spins, num_kpoins, 3, num_bands, num_bands)
    """

    esymbol = endian_symbol(endian)
    # Each complex number takes 2*8 bytes - both real and imaginary parts are
    # double precision - and is wrapped in a pair of 4 byte record markers.
    record_dtype = np.dtype(
        [
            ("head", f"{esymbol}u4"),
            ("value", f"{esymbol}c16"),
            ("tail", f"{esymbol}u4"),
        ]
    )

    if hasattr(fname, "read"):
        raw = fname.read()
    else:
        with open(fname, "rb") as fhandle:
            raw = fhandle.read()

    num_records = num_kpoints * num_spins * 3 * num_bands * num_bands
    expected_size = num_records * record_dtype.itemsize
    if len(raw) != expected_size:
        raise ValueError(
            f"Expected {expected_size} bytes for {num_records} records but the file "
            f"holds {len(raw)} - check num_bands/num_kpoints/num_spins and the endianness."
        )

    records = np.frombuffer(raw, dtype=record_dtype)
    elem_size = record_dtype["value"].itemsize
    if not (
        np.all(records["head"] == elem_size) and np.all(records["tail"] == elem_size)
    ):
        raise ValueError(
            f"Unexpected Fortran record markers - every record should be {elem_size} bytes. "
            "The endianness or the array sizes are probably wrong."
        )

    # Values are written in the order [kpoint][spin][direction][band1][band2]
    om = records["value"].reshape(num_kpoints, num_spins, 3, num_bands, num_bands)
    # Swap to (spin, kpoint, ...) and cast to the native byte order
    return om.transpose(1, 0, 2, 3, 4).astype(complex, order="C")


def read_dome_bin(fname, num_bands, num_kpoints, num_spins, endian="BIG"):
    """
    Read the `dome_bin` file.

    The `dome_bin` file contains the diagonals of the optical matrix (`ome_bin`), which are
    the gradient of the bands. This is file is more compact than `ome_bin` as the diagonal
    elements are real numbers.

    Args:
        fname: Name of the file.
        num_bands: Number of bands.
        num_kpoints: Number of kpoints.
        num_spins: Number of spins.
        endian: Endian - CASTEP build instruction defaults to big-endian.

    Returns:
        version: The version number stored in the file.
        header: Header part written in the file.
        dom: Diagonal elements of the optical matrix with dimensions (num_spin, num_kpoints, 3, num_bands)
    """

    # Each complex number takes 2*8 bits - both real and imaginary parts are
    # double precision
    esymbol = endian_symbol(endian)
    version_dtype = f"{esymbol}f8"
    header_dtype = f"{esymbol}S80"
    array_seg = f"{esymbol}(3,{num_bands})f8"

    dom = np.zeros((num_spins, num_kpoints, 3, num_bands), dtype=float)
    with FortranFile(fname, header_dtype=np.dtype(f"{esymbol}u4")) as fhandle:
        version = fhandle.read_record(version_dtype)
        header = fhandle.read_record(header_dtype)[0].decode()
        for ki in range(num_kpoints):
            for si in range(num_spins):
                dom[si, ki, :, :] = fhandle.read_record(array_seg)
    return version[0], header, dom
