# Build documentation and publish on github pages
on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .[doc]

      - name: Build HTML docs
        id: linkcheck
        run: |
          make -C docs html linkcheck 2>&1 | tee check.log
          echo "::set-output name=broken::$(grep '(line\s*[0-9]*)\(\s\)broken\(\s\)' check.log)"
          echo "::set-output name=ok::$(grep 'build succeed' check.log)"
        env:
          SPHINXOPTS: -nW --keep-going

      - name: Check build status
        run: |
          if [ -z "${{ steps.linkcheck.outputs.ok }}" ]; then
              echo "Build was not successful!"
              exit 1
          else
              echo "Documentation build successful"
              exit 0
          fi

      - name: Show docs build check results
        run: |
          if [ -z "${{ steps.linkcheck.outputs.broken }}" ]; then
              echo "No broken links found."
              exit 0
          else
              echo "Broken links found:"
              echo "${{ steps.linkcheck.outputs.broken }}"
              exit 1
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # Deply the documentation built only on the push even
        if: ${{ (github.event_name != 'pull_request') && (github.repository == 'zhubonan/castepxbin') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
