name: Publish on PyPI

on:
  push:
    tags:
      # After vMajor.Minor.Patch _anything_ is allowed (without "/") !
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'zhubonan/castepxbin' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install flit
      run: |
        python -m pip install --upgrade pip
        python -m pip install flit~=3.4

    - name: Build and publish
      run: |
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD:  ${{ secrets.pypi_token }}
